### ISSUE TITLE
The user type should be an enum.

### ISSUE THREAD

**Issue by masklinn** [octokit/openapi#14]
I expect there are very few values for this property, but it's really unclear what they are or could be aside from `"User"`, which is only given as an example.

Given OpenAPI supports enums, it would make a lot of sense to provide all possible values for this field, or at the very least properly document it to explain what its role and purpose is (or whether it's irrelevant, which doesn't seem to be the case assuming at least one of the other values is `Org` this could be useful for some interactions).

**Comment by masklinn** [comment]
Wrong repository, sorry about that.

**Comment by gr2m** [comment]
As mentioned in #18, the Open API files in https://github.com/octokit/openapi/tree/main/generated are all generated, we do not manually maintain them in this repository. They are downloaded from https://github.com/github/rest-api-description/tree/main/descriptions using an hourly cron job. If you find any problems with the JSON Schema itself that is not part of the x-octokit extension, could you please file it in in https://github.com/github/rest-api-description?

It would be helpful if you could mention the precise location whee the current schema is defined, and how you would change it.

**Comment by gr2m** [comment]
> Wrong repository, sorry about that.

no worries :) I will make it more clear in this repository's README
