### ISSUE TITLE
Examples of error responses seem completely useless.

### ISSUE THREAD

**Issue by masklinn** [octokit/openapi#18]
They seem to be simple copies of the schema (or a pseudo-schema) e.g.

```json
    {
        "message": "string",
        "documentation_url": "string"
    },
```

**Comment by gr2m** [comment]
I checked and didn't find any occurrence of `"documentation_url": "string"`. Where exactly did you find it?

Note that the Open API files in https://github.com/octokit/openapi/tree/main/generated are all generated, we do not manually maintain them in this repository. They are downloaded from https://github.com/github/rest-api-description/tree/main/descriptions using an hourly cron job. If you find any problems with the JSON Schema itself that is not part of the `x-octokit` extension, could you please file it in in https://github.com/github/rest-api-description?

**Comment by masklinn** [comment]
> Note that the Open API files in https://github.com/octokit/openapi/tree/main/generated are all generated, we do not manually maintain them in this repository. They are downloaded from https://github.com/github/rest-api-description/tree/main/descriptions using an hourly cron job.

Ahh crap, I've opened a bunch of garbage in your repository then, sorry about that, I'll close them and re-open them over there.
