### ISSUE TITLE
Should we consider linting this project (the scripts/ folder at least)?

### ISSUE THREAD

**Issue by oscard0m** [octokit/openapi#236]
**What’s missing?**
Lint (Prettier) in this project

**Why?**
For consistency with the rest of the projects of the ecosystem

**Comment by timrogers** [comment]
I’d be very in favour of this ✨ Is there a standard configuration we use?

**Comment by oscard0m** [comment]
> I’d be very in favour of this ✨ Is there a standard configuration we use?

I'm assuming the standard is the one this project proposes for Octokit projects: https://github.com/octokit/create-octokit-project.js/blob/main/lib/create-package-json.js

**Comment by timrogers** [comment]
Nice! Great idea to add it here and bring some order 👌
